import { SMECase, Guideline, Source } from "./types";

export const SAMPLE_GUIDELINES: Guideline[] = [
  {
    id: "g-001",
    sourceName: "NFPA 1582 — Firefighter Cardiovascular Considerations",
    agency: "National Fire Protection Association",
    standardType: "Occupational Medical Standard",
    conditionCategory: "cardiovascular",
    jobCategory: "Firefighter / First Responder",
    summary: "NFPA 1582 addresses medical requirements for fire department members. Cardiovascular conditions may be relevant given the extreme physical demands, thermal stress, and sudden exertion involved in firefighting duties.",
    medicalTriggers: "Coronary artery disease, hypertension, arrhythmia, cardiomyopathy, recent cardiac events, uncontrolled cardiac conditions",
    jobDutyTriggers: "Emergency response, wearing SCBA, extreme heat exposure, prolonged exertion, wearing full PPE and body armor",
    documentationNeeded: "Cardiology evaluation, stress test results, echocardiogram if applicable, current medication list, provider statement on functional capacity",
    riskConsiderations: "Sudden incapacitation risk in safety-sensitive environment; thermal/exertion cardiovascular strain; SCBA breathing resistance; emergency decision-making under physical duress",
    sourceLink: "https://www.nfpa.org/codes-and-standards/1/5/8/2/NFPA-1582",
    lastReviewed: "2024-01-01",
    reviewedBy: "SAMPLE",
    sourceConfidence: "official",
    versionDate: "2022",
    notes: "SAMPLE ONLY — This is a placeholder example. Replace with reviewed official guidance before production use.",
    isSample: true
  },
  {
    id: "g-002",
    sourceName: "FAA Sudden Incapacitation Considerations",
    agency: "Federal Aviation Administration",
    standardType: "Aviation Medical Standard",
    conditionCategory: "neurologic",
    jobCategory: "Aviation Safety-Sensitive",
    summary: "FAA medical standards address conditions that may cause sudden incapacitation in aviation safety-sensitive roles. Neurologic and cardiac conditions are primary considerations given cockpit safety requirements.",
    medicalTriggers: "Seizure disorder, syncope, cardiac arrhythmia, uncontrolled hypertension, psychiatric instability, medication sedation, vision/hearing impairment",
    jobDutyTriggers: "Aircraft operation, flight deck duties, air traffic control, aviation safety-sensitive functions",
    documentationNeeded: "Neurology evaluation, EEG if applicable, cardiology evaluation, complete medication list with side effect profile, psychiatric evaluation if relevant, vision and hearing testing",
    riskConsiderations: "Sudden incapacitation at altitude; medication side effects affecting cognition, reaction time, or alertness; psychiatric stability under high-stress aviation environment",
    sourceLink: "https://www.faa.gov/licenses_certificates/medical_certification",
    lastReviewed: "2024-01-01",
    reviewedBy: "SAMPLE",
    sourceConfidence: "official",
    versionDate: "2024",
    notes: "SAMPLE ONLY — This is a placeholder example. Replace with reviewed official guidance before production use.",
    isSample: true
  },
  {
    id: "g-003",
    sourceName: "MOD Deployment Chronic Disease Stability Considerations",
    agency: "Ministry of Defence (MOD)",
    standardType: "Military Deployment Medical Standard",
    conditionCategory: "other",
    jobCategory: "Military / Defense Deployment",
    summary: "MOD deployment medical standards address chronic disease stability, medication access in austere environments, emergency care limitations, and fitness for deployment duties in remote or hostile locations.",
    medicalTriggers: "Insulin-dependent diabetes, seizure disorder, cardiac disease, psychiatric conditions requiring monitoring, chronic conditions requiring specialty care or refrigerated medications",
    jobDutyTriggers: "Remote deployment, austere location, limited medical care, extreme climate, restricted pharmacy access, prolonged separation from specialty care",
    documentationNeeded: "Current condition stability documentation, complete medication list, refrigeration requirements, specialty follow-up schedule, provider statement on deployment tolerance",
    riskConsiderations: "Medication storage and access in austere settings; distance from emergency/specialty care; exacerbation risk in extreme climates; evacuation delay risk",
    sourceLink: "",
    lastReviewed: "2024-01-01",
    reviewedBy: "SAMPLE",
    sourceConfidence: "internal",
    versionDate: "2023",
    notes: "SAMPLE ONLY — This is a placeholder example. Replace with reviewed official guidance before production use.",
    isSample: true
  },
  {
    id: "g-004",
    sourceName: "DOT/FMCSA Safety-Sensitive Commercial Driver Considerations",
    agency: "Department of Transportation / FMCSA",
    standardType: "DOT Medical Standard",
    conditionCategory: "cardiovascular",
    jobCategory: "Commercial Driver / Vehicle Operator",
    summary: "DOT/FMCSA medical standards address conditions relevant to safe commercial vehicle operation. Sudden incapacitation, vision, hearing, and medication side effects are primary considerations for safety-sensitive driving roles.",
    medicalTriggers: "Seizure disorder, syncope, insulin-dependent diabetes, severe hypertension, cardiovascular disease, sleep apnea, sedating medications, psychiatric instability, vision/hearing deficits",
    jobDutyTriggers: "Commercial vehicle operation, extended driving, driving alone, driving in variable conditions, operating heavy equipment",
    documentationNeeded: "Current condition stability, medication list with sedation potential, vision and hearing results, sleep study if sleep apnea suspected, neurology/cardiology documentation as applicable",
    riskConsiderations: "Sudden incapacitation while operating commercial vehicle; medication side effects impairing reaction time or cognition; fatigue-related risk from sleep disorders",
    sourceLink: "https://www.fmcsa.dot.gov/medical",
    lastReviewed: "2024-01-01",
    reviewedBy: "SAMPLE",
    sourceConfidence: "official",
    versionDate: "2023",
    notes: "SAMPLE ONLY — This is a placeholder example. Replace with reviewed official guidance before production use.",
    isSample: true
  },
  {
    id: "g-005",
    sourceName: "OSHA Heat Exposure Occupational Considerations",
    agency: "Occupational Safety and Health Administration",
    standardType: "Occupational Health Guideline",
    conditionCategory: "cardiovascular",
    jobCategory: "Heat-Exposed Occupations",
    summary: "OSHA heat illness prevention guidelines address medical risk factors that increase vulnerability to heat stress and heat illness in occupational settings involving extreme heat exposure.",
    medicalTriggers: "Cardiovascular disease, diabetes, obesity, hypertension, medications affecting heat regulation (diuretics, beta-blockers, anticholinergics), dehydration risk",
    jobDutyTriggers: "Extreme heat exposure, wearing PPE in heat, outdoor work in summer, working near heat sources, limited access to shade/water/cooling",
    documentationNeeded: "Cardiovascular evaluation if cardiac history, medication list for heat-affecting medications, provider statement on heat tolerance",
    riskConsiderations: "Increased heat illness risk with cardiac conditions; medication interference with heat regulation; reduced heat tolerance in individuals with diabetes or obesity",
    sourceLink: "https://www.osha.gov/heat",
    lastReviewed: "2024-01-01",
    reviewedBy: "SAMPLE",
    sourceConfidence: "official",
    versionDate: "2024",
    notes: "SAMPLE ONLY — This is a placeholder example. Replace with reviewed official guidance before production use.",
    isSample: true
  },
  {
    id: "g-006",
    sourceName: "NIOSH Respiratory Exposure Occupational Considerations",
    agency: "National Institute for Occupational Safety and Health",
    standardType: "Occupational Health Guideline",
    conditionCategory: "respiratory",
    jobCategory: "Industrial / Firefighter / Construction",
    summary: "NIOSH guidelines address respiratory disease considerations for occupations with significant airborne hazard exposure including smoke, dust, fumes, and chemical agents.",
    medicalTriggers: "Asthma, COPD, restrictive lung disease, occupational asthma, reactive airway disease, respiratory infections",
    jobDutyTriggers: "Wearing SCBA or respirator, dust/fume exposure, smoke exposure, poor air quality environment, confined space work",
    documentationNeeded: "Pulmonary function testing (spirometry), chest imaging if indicated, provider statement on respirator tolerance, medication list",
    riskConsiderations: "Respirator tolerance with obstructive lung disease; exacerbation risk with respiratory chemical exposure; SCBA physical burden with reduced pulmonary reserve",
    sourceLink: "https://www.cdc.gov/niosh",
    lastReviewed: "2024-01-01",
    reviewedBy: "SAMPLE",
    sourceConfidence: "official",
    versionDate: "2023",
    notes: "SAMPLE ONLY — This is a placeholder example. Replace with reviewed official guidance before production use.",
    isSample: true
  },
  {
    id: "g-007",
    sourceName: "BLS Musculoskeletal Injury Context",
    agency: "Bureau of Labor Statistics",
    standardType: "Occupational Injury Data Reference",
    conditionCategory: "orthopedic",
    jobCategory: "Construction / Labor / Physical Trades",
    summary: "BLS occupational injury data provides context on musculoskeletal injury prevalence, mechanisms, and reinjury risk patterns across physically demanding occupations.",
    medicalTriggers: "Prior back injury, prior extremity injury, chronic musculoskeletal conditions, prior surgery with residual limitations, ongoing physical therapy",
    jobDutyTriggers: "Lifting/carrying, prolonged standing, climbing, kneeling, bending, pushing/pulling, confined spaces, physically demanding tasks",
    documentationNeeded: "Functional capacity evaluation if available, imaging results, PT discharge summary, provider statement on functional restrictions",
    riskConsiderations: "Reinjury risk with prior musculoskeletal injury; functional limitation relevance to physical job demands; cumulative strain risk with residual weakness or reduced ROM",
    sourceLink: "https://www.bls.gov/iif/",
    lastReviewed: "2024-01-01",
    reviewedBy: "SAMPLE",
    sourceConfidence: "official",
    versionDate: "2023",
    notes: "SAMPLE ONLY — This is a placeholder example. Replace with reviewed official guidance before production use.",
    isSample: true
  },
  {
    id: "g-008",
    sourceName: "CDC Country Travel Health Considerations",
    agency: "Centers for Disease Control and Prevention",
    standardType: "Travel / Deployment Health Guidance",
    conditionCategory: "infectious-disease",
    jobCategory: "International Deployment / Travel",
    summary: "CDC travel health guidance addresses country-specific infectious disease risks, vaccine requirements, medication needs, and health precautions relevant to international deployment and travel.",
    medicalTriggers: "Immunocompromised conditions, immunosuppressive medications, chronic respiratory conditions, diabetes, renal disease",
    jobDutyTriggers: "International deployment, remote location, limited medical care, food/water safety risk, vector-borne disease exposure",
    documentationNeeded: "Vaccination history, medication interactions with prophylaxis medications, immune status if relevant",
    riskConsiderations: "Increased infectious disease susceptibility in immunocompromised individuals; medication interactions with required prophylaxis; access to treatment in resource-limited settings",
    sourceLink: "https://wwwnc.cdc.gov/travel",
    lastReviewed: "2024-01-01",
    reviewedBy: "SAMPLE",
    sourceConfidence: "official",
    versionDate: "2024",
    notes: "SAMPLE ONLY — This is a placeholder example. Replace with reviewed official guidance before production use.",
    isSample: true
  },
  {
    id: "g-009",
    sourceName: "Client-Specific Deployment Medical Requirements",
    agency: "Client / Contracting Organization (Placeholder)",
    standardType: "Client-Specific Standard",
    conditionCategory: "other",
    jobCategory: "Contractor / Client Deployment",
    summary: "Client-specific deployment medical requirements vary by contract and agency. This placeholder entry should be replaced with the specific requirements of the client or contracting organization.",
    medicalTriggers: "Varies by client standard — document here after review",
    jobDutyTriggers: "Varies by client standard — document here after review",
    documentationNeeded: "Per client requirements — document here after review",
    riskConsiderations: "Varies by client standard — document here after review",
    sourceLink: "",
    lastReviewed: "2024-01-01",
    reviewedBy: "SAMPLE",
    sourceConfidence: "internal",
    versionDate: "2024",
    notes: "SAMPLE ONLY — This is a placeholder example. Replace with the actual client-specific requirements before production use.",
    isSample: true
  }
];

export const SAMPLE_SOURCES: Source[] = [
  {
    id: "s-001",
    title: "NFPA 1582: Standard on Comprehensive Occupational Medical Program for Fire Departments",
    organization: "National Fire Protection Association",
    url: "https://www.nfpa.org/codes-and-standards/1/5/8/2/NFPA-1582",
    publicationDate: "2022-01-01",
    lastReviewed: "2024-01-01",
    reviewedBy: "SAMPLE",
    summary: "Establishes medical requirements for fire department candidates and members. Includes Category A and Category B conditions relevant to firefighting duties.",
    relevantConditions: "Cardiovascular disease, respiratory disease, neurologic conditions, psychiatric conditions, diabetes, orthopedic conditions",
    relevantJobs: "Firefighter, first responder, fire inspector",
    relevantCountries: "",
    sourceReliability: "High",
    notes: "SAMPLE ONLY",
    createdAt: new Date().toISOString()
  },
  {
    id: "s-002",
    title: "FMCSA Medical Examiner Handbook",
    organization: "Federal Motor Carrier Safety Administration",
    url: "https://www.fmcsa.dot.gov/medical",
    publicationDate: "2023-01-01",
    lastReviewed: "2024-01-01",
    reviewedBy: "SAMPLE",
    summary: "Guidance for medical examiners performing DOT/FMCSA examinations for commercial motor vehicle operators.",
    relevantConditions: "Cardiovascular, neurologic, psychiatric, sleep disorders, diabetes, vision/hearing",
    relevantJobs: "Commercial driver, heavy equipment operator",
    relevantCountries: "",
    sourceReliability: "High",
    notes: "SAMPLE ONLY",
    createdAt: new Date().toISOString()
  }
];

export const SAMPLE_CASES: SMECase[] = [
  {
    id: "case-001",
    caseId: "SME-2024-001",
    examineeName: "J.M.",
    dob: "1979-03-15",
    age: 45,
    sex: "Male",
    employer: "Regional Fire Authority",
    jobTitle: "Senior Firefighter / Paramedic",
    department: "Operations — Station 7",
    examType: "annual",
    reviewingSME: "Dr. K. Harrington, MRO",
    caseManager: "L. Vasquez",
    dateOfExam: "2024-11-12",
    workLocation: "Metro Region",
    deploymentCountry: "",
    agencyStandard: "NFPA 1582",
    standards: {
      selected: ["NFPA firefighter", "OSHA"],
      customNotes: "Agency requires NFPA 1582 compliance with annual medical surveillance"
    },
    notes: "DEMO CASE — Annual medical surveillance exam. Examinee is an active firefighter with reported cardiovascular history.",
    status: "Risk Review Needed",
    createdAt: "2024-11-12T10:00:00Z",
    updatedAt: "2024-11-14T14:30:00Z",
    medicalConditions: [
      {
        id: "mc-001",
        conditionName: "Hypertension",
        category: "cardiovascular",
        dateDiagnosed: "2019-06-01",
        status: "stable",
        symptoms: "Occasional headache",
        severity: 3,
        frequencyOfSymptoms: "Occasional",
        lastFlare: "2024-08-01",
        treatmentPlan: "Antihypertensive medication, dietary modifications",
        currentMedications: "Lisinopril 10mg daily",
        medicationSideEffects: "Mild dry cough reported",
        specialist: "Primary care physician",
        hospitalizations: 0,
        erVisits: 0,
        surgeries: 0,
        recentLabs: "BP 138/88 at last check; metabolic panel WNL",
        providerQuote: "Blood pressure is currently managed on single-agent therapy. Monitoring every 6 months.",
        selfReported: "Examinee reports compliance with medication. Denies chest pain or syncope.",
        functionalLimitations: "None reported",
        restrictions: "None documented",
        monitoringRequirements: "BP monitoring q6 months",
        incapacitationRisk: "Possible",
        recurrenceRisk: "Moderate",
        refrigerationNeeded: false,
        specialtyFollowUp: false,
        emergencyAccessNeeded: false,
        notes: "On single antihypertensive agent; BP trending toward upper normal range at last documentation"
      },
      {
        id: "mc-002",
        conditionName: "Obstructive Sleep Apnea",
        category: "sleep-disorder",
        dateDiagnosed: "2022-09-01",
        status: "stable",
        symptoms: "Daytime fatigue when non-compliant",
        severity: 4,
        frequencyOfSymptoms: "When CPAP non-compliant",
        lastFlare: "",
        treatmentPlan: "CPAP therapy nightly",
        currentMedications: "None",
        medicationSideEffects: "",
        specialist: "Pulmonology / Sleep Medicine",
        hospitalizations: 0,
        erVisits: 0,
        surgeries: 0,
        recentLabs: "Sleep study: AHI 22 (moderate OSA); CPAP compliance reported at 80%",
        providerQuote: "Patient is using CPAP with reported compliance. Symptoms well-controlled on therapy.",
        selfReported: "Reports using CPAP regularly. Denies excessive daytime sleepiness when compliant.",
        functionalLimitations: "Fatigue if CPAP unavailable",
        restrictions: "CPAP required for optimal function",
        monitoringRequirements: "Annual sleep medicine follow-up",
        incapacitationRisk: "Possible",
        recurrenceRisk: "Moderate",
        refrigerationNeeded: false,
        specialtyFollowUp: true,
        emergencyAccessNeeded: false,
        notes: "CPAP dependency relevant to deployment settings with unreliable power"
      }
    ],
    injuries: [
      {
        id: "inj-001",
        injuryType: "Lumbar Strain / Disc Herniation",
        bodyRegion: "Lower Back (L4-L5)",
        dateOfInjury: "2021-03-10",
        mechanism: "Lifting patient during emergency response",
        treatmentReceived: "Physical therapy x 12 weeks, NSAIDs",
        surgeriesPerformed: "None",
        ptReceived: true,
        imagingType: "MRI lumbar spine — disc herniation L4-L5 with mild foraminal narrowing",
        residualPain: 2,
        residualWeakness: "Mild",
        romLimitation: "Mild reduced lumbar flexion at extremes",
        workRestrictions: "Light duty x 6 weeks (now resolved)",
        reinjuryRisk: "Moderate",
        jobDutyRelevance: "May be relevant to lifting, carrying, and prolonged physical exertion duties",
        providerQuote: "Patient has returned to full duty. Residual mild discomfort noted at extremes of range. Reinjury risk should be considered with heavy lifting.",
        documentationConfidence: "documented"
      }
    ],
    jobDuties: {
      physicalDemands: ["lifting", "carrying", "climbing", "crawling", "wearing PPE", "wearing respirator", "emergency response", "confined spaces", "heat exposure"],
      cognitiveDemands: ["high-stress decision-making", "situational awareness", "emergency judgment", "shift work", "public safety"],
      environmentalDemands: ["extreme heat", "poor air quality", "limited medical care"],
      essentialFunctions: "Responds to structure fires, medical emergencies, hazmat incidents. Required to wear full SCBA and turnout gear. Performs physical rescue operations including victim extrication, hose advancement, and ladder operations.",
      clientRequirements: "NFPA 1582 compliance required for all operational firefighters",
      agencyStandardNotes: "Annual medical surveillance per department protocol"
    },
    countryRisk: null,
    occupationalData: {
      jobCategory: "Firefighter",
      commonInjuryPatterns: "Cardiovascular events during active suppression; musculoskeletal injury during rescue operations; smoke/chemical inhalation; thermal injuries",
      fatalityRiskFactors: "Sudden cardiac death is leading cause of on-duty firefighter fatalities; structure collapse; vehicle accidents",
      mskPrevalence: "High — back, shoulder, and knee injuries are most prevalent",
      heatIllnessRisk: "High — thermal stress from turnout gear and fire environment",
      respiratoryRisk: "Moderate-High — smoke and chemical inhalation risk despite SCBA",
      transportationRisk: "Moderate — emergency vehicle operations",
      violenceRisk: "Low-Moderate",
      slipsTripsFalls: "Moderate — uneven terrain in fire structures",
      overexertion: "High",
      hazardousExposure: "High — chemical, biological, radiological potential",
      source: "BLS / NIOSH / IAFF",
      sourceDate: "2023",
      notes: "Firefighter cardiovascular risk is well-documented in occupational literature"
    },
    healthEquity: {
      accessToCare: "Adequate access — employer-sponsored healthcare",
      transportationBarriers: false,
      transportationNotes: "",
      medicationAffordability: false,
      medicationAffordabilityNotes: "",
      insuranceLimitations: "",
      localProviderAvailability: "Good",
      specialistAccess: "Good",
      pharmacyAccess: "Good",
      languageSupport: false,
      languageNotes: "",
      healthLiteracySupport: false,
      healthLiteracyNotes: "",
      followUpFeasibility: "Easy",
      documentationBarriers: "",
      supportRecommendations: "No identified access barriers. Standard follow-up recommended."
    },
    riskScores: [],
    documentationGaps: [],
    smeAssessment: {
      clinicalInterpretation: "",
      occupationalRelevance: "",
      riskLevel: "",
      documentationSufficiency: "",
      additionalRecordsNeeded: "",
      finalRecommendation: "",
      recommendationFreeText: "",
      smeReviewNotes: "",
      documentsReviewed: ["Medical history questionnaire", "Exam forms"],
      dateCompleted: ""
    }
  },
  {
    id: "case-002",
    caseId: "SME-2024-002",
    examineeName: "A.R.",
    dob: "1985-07-22",
    age: 39,
    sex: "Female",
    employer: "Defense Contracting Group",
    jobTitle: "Medical Support Specialist",
    department: "Forward Support Unit",
    examType: "deployment",
    reviewingSME: "Dr. P. Steinberg, MPH",
    caseManager: "T. Nguyen",
    dateOfExam: "2024-10-03",
    workLocation: "To be deployed",
    deploymentCountry: "Kuwait",
    agencyStandard: "MOD / Client Deployment Standard",
    standards: {
      selected: ["MOD deployment", "CDC travel health"],
      customNotes: "Client requires full deployment medical clearance package"
    },
    notes: "DEMO CASE — Deployment medical exam for contracted medical support role. Deployment to Kuwait anticipated.",
    status: "Needs Records",
    createdAt: "2024-10-03T09:00:00Z",
    updatedAt: "2024-10-10T11:00:00Z",
    medicalConditions: [
      {
        id: "mc-003",
        conditionName: "Type 2 Diabetes Mellitus",
        category: "endocrine-metabolic",
        dateDiagnosed: "2020-02-01",
        status: "stable",
        symptoms: "None at baseline",
        severity: 3,
        frequencyOfSymptoms: "None at baseline",
        lastFlare: "",
        treatmentPlan: "Oral agents, dietary management",
        currentMedications: "Metformin 1000mg BID, Glipizide 5mg daily",
        medicationSideEffects: "Mild GI symptoms with Metformin initially; resolved",
        specialist: "Endocrinology",
        hospitalizations: 0,
        erVisits: 0,
        surgeries: 0,
        recentLabs: "HbA1c 7.2% (3 months ago); fasting glucose 118",
        providerQuote: "Diabetes is well-controlled on current oral regimen. No evidence of hypoglycemic episodes documented.",
        selfReported: "Reports compliance with medications. Denies hypoglycemic episodes. Carries snacks.",
        functionalLimitations: "None at baseline",
        restrictions: "None documented",
        monitoringRequirements: "HbA1c q3 months; annual ophthalmology and podiatry",
        incapacitationRisk: "Possible",
        recurrenceRisk: "Moderate",
        refrigerationNeeded: false,
        specialtyFollowUp: true,
        emergencyAccessNeeded: false,
        notes: "On sulfonylurea — hypoglycemia risk should be assessed in context of deployment duties and heat exposure"
      }
    ],
    injuries: [],
    jobDuties: {
      physicalDemands: ["lifting", "carrying", "prolonged standing", "prolonged walking", "heat exposure"],
      cognitiveDemands: ["high-stress decision-making", "situational awareness", "patient care", "working alone"],
      environmentalDemands: ["austere location", "remote site", "extreme heat", "limited pharmacy access", "limited specialty care", "evacuation delays"],
      essentialFunctions: "Provides medical support at forward deployed location. Manages medical supplies. Provides first aid and medical assistance to contractor personnel. Works in austere environment with limited medical backup.",
      clientRequirements: "Deployment requires medical self-sufficiency; limited medevac availability",
      agencyStandardNotes: "Client requires documentation of chronic disease stability and medication supply plan"
    },
    countryRisk: {
      country: "Kuwait",
      region: "Middle East / Gulf Region",
      climateRisks: ["extreme heat", "humidity", "desert/dust"],
      infectiousDiseaseRisks: ["diarrheal illness"],
      vaccineRequirements: "Standard deployment vaccinations required per client protocol",
      medicationAvailability: "Limited local pharmacy access; medications should be brought in adequate supply",
      localMedicalInfrastructure: "Limited",
      evacuationConcerns: "Evacuation protocols exist but delays of 24-72 hours are possible",
      specialtyCareAvailability: "Limited endocrinology; basic emergency care available on base",
      pharmacyReliability: "Limited",
      securityRisk: "Moderate",
      foodWaterSafety: "Moderate risk — bottled water recommended; dietary adjustments needed",
      occupationalExposureRisks: "Sand/dust exposure; extreme heat; potential chemical exposure at certain sites",
      notes: "Extreme heat is a primary environmental risk. Diabetes + heat exposure + sulfonylurea = hypoglycemia and heat illness risk requiring documentation and planning.",
      sourceLink: "https://wwwnc.cdc.gov/travel/destinations/traveler/none/kuwait",
      lastReviewed: "2024-01-01"
    },
    occupationalData: null,
    healthEquity: {
      accessToCare: "Adequate home access; deployment access is limited",
      transportationBarriers: false,
      transportationNotes: "",
      medicationAffordability: false,
      medicationAffordabilityNotes: "",
      insuranceLimitations: "",
      localProviderAvailability: "Limited",
      specialistAccess: "Limited",
      pharmacyAccess: "Limited",
      languageSupport: false,
      languageNotes: "",
      healthLiteracySupport: false,
      healthLiteracyNotes: "",
      followUpFeasibility: "Difficult",
      documentationBarriers: "Remote deployment will limit ability to complete follow-up lab monitoring during deployment period",
      supportRecommendations: "Pre-deployment: obtain 90-day medication supply; confirm HbA1c before departure; document hypoglycemia action plan; establish emergency contact protocol"
    },
    riskScores: [],
    documentationGaps: [],
    smeAssessment: {
      clinicalInterpretation: "",
      occupationalRelevance: "",
      riskLevel: "",
      documentationSufficiency: "",
      additionalRecordsNeeded: "Endocrinology letter addressing heat exposure and hypoglycemia risk during deployment; medication supply plan",
      finalRecommendation: "",
      recommendationFreeText: "",
      smeReviewNotes: "",
      documentsReviewed: ["Medical history questionnaire", "Medication list", "Recent labs"],
      dateCompleted: ""
    }
  },
  {
    id: "case-003",
    caseId: "SME-2024-003",
    examineeName: "D.O.",
    dob: "1990-11-05",
    age: 34,
    sex: "Male",
    employer: "Regional Transit Authority",
    jobTitle: "Commercial Bus Operator",
    department: "Operations",
    examType: "dot-fmcsa",
    reviewingSME: "Dr. W. Chen, CME",
    caseManager: "R. Thompson",
    dateOfExam: "2024-09-18",
    workLocation: "Metropolitan Transit District",
    deploymentCountry: "",
    agencyStandard: "DOT/FMCSA",
    standards: {
      selected: ["DOT/FMCSA", "OSHA"],
      customNotes: ""
    },
    notes: "DEMO CASE — DOT/FMCSA commercial driver medical examination. History of seizure disorder.",
    status: "Ready for SME",
    createdAt: "2024-09-18T08:00:00Z",
    updatedAt: "2024-09-25T16:00:00Z",
    medicalConditions: [
      {
        id: "mc-004",
        conditionName: "Seizure Disorder — Epilepsy",
        category: "neurologic",
        dateDiagnosed: "2016-04-01",
        status: "stable",
        symptoms: "None — seizure-free on current regimen",
        severity: 6,
        frequencyOfSymptoms: "None at current",
        lastFlare: "2021-08-15",
        treatmentPlan: "Anticonvulsant therapy",
        currentMedications: "Levetiracetam 1000mg BID",
        medicationSideEffects: "Mild fatigue and mood changes reported",
        specialist: "Neurology",
        hospitalizations: 1,
        erVisits: 2,
        surgeries: 0,
        recentLabs: "Drug level therapeutic; MRI brain — no acute abnormality; EEG 6 months ago WNL",
        providerQuote: "Patient has been seizure-free for 3 years on current anticonvulsant regimen. Neurologic exam is normal. Drug level is therapeutic.",
        selfReported: "Reports compliance with medication. Denies breakthrough events. Reports occasional fatigue.",
        functionalLimitations: "None at baseline on medication",
        restrictions: "State driving restriction — cleared by neurology after 3-year seizure-free period",
        monitoringRequirements: "Annual neurology follow-up; drug level monitoring",
        incapacitationRisk: "Possible",
        recurrenceRisk: "Moderate",
        refrigerationNeeded: false,
        specialtyFollowUp: true,
        emergencyAccessNeeded: false,
        notes: "Sudden incapacitation risk is the primary concern in context of safety-sensitive vehicle operation. Medication side effects (fatigue) may also be relevant."
      }
    ],
    injuries: [],
    jobDuties: {
      physicalDemands: ["prolonged standing", "prolonged walking", "driving", "operating machinery"],
      cognitiveDemands: ["situational awareness", "public safety", "vehicle operation", "shift work", "night work"],
      environmentalDemands: [],
      essentialFunctions: "Operates large commercial passenger buses on fixed transit routes. Responsible for passenger safety. Works variable shifts including nights and weekends.",
      clientRequirements: "DOT/FMCSA medical certificate required. Agency requires CME examination.",
      agencyStandardNotes: "DOT regulations address seizure disorder for commercial drivers."
    },
    countryRisk: null,
    occupationalData: {
      jobCategory: "Driver / Commercial Vehicle Operator",
      commonInjuryPatterns: "Musculoskeletal — prolonged sitting; eye strain; stress-related conditions",
      fatalityRiskFactors: "Vehicle crashes; medical events behind the wheel",
      mskPrevalence: "Moderate — lower back, neck, upper extremity",
      heatIllnessRisk: "Low-Moderate",
      respiratoryRisk: "Low",
      transportationRisk: "High — primary occupational risk",
      violenceRisk: "Moderate — public transit passenger incidents",
      slipsTripsFalls: "Low",
      overexertion: "Low",
      hazardousExposure: "Low",
      source: "BLS / FMCSA",
      sourceDate: "2023",
      notes: "Sudden medical incapacitation behind the wheel is the primary safety-sensitive concern for this role"
    },
    healthEquity: {
      accessToCare: "Adequate",
      transportationBarriers: false,
      transportationNotes: "",
      medicationAffordability: false,
      medicationAffordabilityNotes: "",
      insuranceLimitations: "",
      localProviderAvailability: "Good",
      specialistAccess: "Good",
      pharmacyAccess: "Good",
      languageSupport: false,
      languageNotes: "",
      healthLiteracySupport: false,
      healthLiteracyNotes: "",
      followUpFeasibility: "Easy",
      documentationBarriers: "",
      supportRecommendations: "No identified access barriers."
    },
    riskScores: [],
    documentationGaps: [],
    smeAssessment: {
      clinicalInterpretation: "",
      occupationalRelevance: "",
      riskLevel: "",
      documentationSufficiency: "",
      additionalRecordsNeeded: "",
      finalRecommendation: "",
      recommendationFreeText: "",
      smeReviewNotes: "",
      documentsReviewed: ["Medical history questionnaire", "Exam forms", "Neurology letter", "Drug levels", "EEG results"],
      dateCompleted: ""
    }
  }
];
